#!/bin/sh
set -e

time python src/filter_page_links_by_frequency.py
time python src/create_dictionary.py
time python src/create_corpus.py
time python src/train_model.py
time python src/create_index.py
time python src/present_model.py

ls -lh tmp/
